# -*- coding: utf-8 -*-
"""tic-tac.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NgwkwtbeG6uCzv2Au5rOGx_TOIWgOKl7

#tic-tac game
"""

import numpy as np
game=np.array(["-","-","-","-","-","-","-","-","-"])
print(game.reshape(3,3))

step=0
flag=0
win=0
while step<9:


  if flag==0:                                              # step of player 1st
    inp=int(input("enter step of 1st player  : "))


    while inp>9 or game[inp-1]=="X" or game[inp-1]=="O":
      print(" Pls enter in between 1 to 9  and write only in empty space")
      inp = int(input("enter step of 1st player  : "))


    game[inp-1]="O"
    print(game.reshape(3,3))
    flag=flag+1
    step+=1
  
  else:                                                 #step of player 2nd
    inp=int(input("enter step of 2nd player : "))

    while inp > 9 or game[inp-1]=="X" or game[inp-1]=="O":
      print(" Pls enter in between 1 to 9 and write only in empty space ")
      inp = int(input("enter step of 2nd  player  : "))


    game[inp-1]="X"
    flag=flag-1
    step+=1
    print(game.reshape(3,3))

  if ((game[0]=="O" and game[1]=="O" and game[2]=="O") or (game[3]=="O" and game[4]=="O" and game[5]=="O") or (game[6]=="O" and game[7]=="O" and game[8]=="O") or
      (game[0]=="O" and game[3]=="O" and game[6]=="O") or (game[1]=="O" and game[4]=="O" and game[7]=="O") or (game[2]=="O" and game[5]=="O" and game[8]=="O") or
      (game[0]=="O" and game[4]=="O" and game[8]=="O") or (game[2]=="O" and game[4]=="O" and game[6]=="O")):
    
    print("\n ----player 1 win----")
    win=win+1
    break

  if ( (game[0]=="X" and game[1]=="X" and game[2]=="X") or (game[3]=="X" and game[4]=="X" and game[5]=="X") or (game[6]=="X" and game[7]=="X" and game[8]=="X") or
       (game[0]=="X" and game[3]=="X" and game[6]=="X") or (game[1]=="X" and game[4]=="X" and game[7]=="X") or (game[2]=="X" and game[5]=="X" and game[8]=="X") or
       (game[0]=="X" and game[4]=="X" and game[8]=="X") or (game[2]=="X" and game[4]=="X" and game[6]=="X") ):
    print("\n ----player 2 win----")
    win=win+1
    break


if win==0:
  print(" \n Match is draw")